// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/squad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/squad">> = Specific
  const handler = {} as typeof import("../../../../src/app/squad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approve">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/audit-action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-action">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/audit-action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/mcp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mcp">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/mcp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pending">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/pipeline-control/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline-control">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/pipeline-control/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/provider-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider-config">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/provider-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/providers">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reset">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/resume-pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resume-pipeline">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/resume-pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/skill/dev-squad/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/skill/dev-squad">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/skill/dev-squad/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/start-pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/start-pipeline">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/start-pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/state">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/stop-pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stop-pipeline">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/stop-pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
